export const SET_WORD = 'SET_WORD';
export const SET_TRANSLATION = 'SET_TRANSLATION';
export const SET_SUGESTIONS = 'SET_SUGESTIONS';
export const RESET_RECENT = 'RESET_RECENT';
export const SET_RECENT = 'SET_RECENT';
export const SET_TYPES = 'SET_TYPES';

export const SET_SEARCH_MODE = 'SET_SEARCH_MODE';
export const REMOVE_SEARCH_MODE = 'REMOVE_SEARCH_MODE';

export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const REMOVE_SEARCH_LOADING = 'REMOVE_SEARCH_LOADING';

export const SET_CONTENT_LOADING = 'SET_CONTENT_LOADING';
export const REMOVE_CONTENT_LOADING = 'REMOVE_CONTENT_LOADING';

export const SET_THERE_SUGESTIONS = 'SET_THERE_SUGESTIONS';
export const REMOVE_THERE_SUGESTIONS = 'REMOVE_THERE_SUGESTIONS';